import numpy as np
from scipy.interpolate import interp1d

G = 4.30091e-6  # kpc * (km/s)^2 / M_sun

# --- Eccentricity distributions ---
# these e values are generated by inverse transform sampling the given PDFs (y) in the paper. i.e take the integral of the PDFs
# from zero to x then invert the equation by replacing y <-> x and solve for y.
def sample_eccentricity(model, size=1):
    u = np.random.uniform(size=size)
    if model == 'f1': return np.zeros(size)
    elif model == 'f2': return 1 - np.sqrt(1 - u)
    elif model == 'f3': return u
    elif model == 'f4': return np.sqrt(u)
    elif model == 'f5': return np.full(size, 0.9)
    else: raise ValueError("Invalid eccentricity model")

# --- Solve Kepler's equation ---
def solve_kepler(M, e, tol=1e-12, max_iter=60):
    """Vectorised Newton-Raphson solution of E - e*sin(E) = M.

    Replaces scipy.optimize.fsolve, which treated the whole array as a single
    coupled system and was orders of magnitude slower for no benefit -- the
    equation is separable, one independent root per element.
    """
    M = np.asarray(M, dtype=float)
    e = np.broadcast_to(np.asarray(e, dtype=float), M.shape).copy()
    E = M + e * np.sin(M)          # standard first-order starter
    for _ in range(max_iter):
        dE = (E - e * np.sin(E) - M) / (1.0 - e * np.cos(E))
        E -= dE
        if np.max(np.abs(dE)) < tol:
            break
    return E

# --- Build r sampler from given distribution ---
def build_r_sampler(r_vals, f_r):
    cdf = np.cumsum(f_r)
    cdf /= cdf[-1]
    return interp1d(cdf, r_vals, bounds_error=False, fill_value=(r_vals[0], r_vals[-1]))

# --- Sample psi values ---
def sample_psi(e_model, r, n_samples):
    """Sample the mass-independent speed psi = |v| / sqrt(M) and the orbital
    geometry needed to project it.

    For a Kepler orbit  v^2 = G*M*(1 + e*cos E)/r,  so psi = sqrt(G*(1+e cos E)/r)
    carries no dependence on the total mass.

    Returns
    -------
    psi : ndarray
        |v| / sqrt(M),  units (km/s) / sqrt(M_sun).
    phi : ndarray
        Flight-path angle: the angle between the velocity vector and the
        direction perpendicular to the separation vector, within the orbital
        plane.  tan(phi) = e*sin(E) / sqrt(1 - e^2).

        This is what fixes the relative orientation of r and v.  The caller
        needs it in order to project BOTH vectors onto a single, shared line
        of sight (see Binary_87_Para_Main_2).

    Note
    ----
    r is drawn from the deconvolved f(r) while the orbital phase is drawn
    uniform in mean anomaly, independently.  For a true orbit these are linked
    by r = a*(1 - e*cos E), so conditioning on r would skew the phase
    distribution towards apocentre.  This independence is inherited from the
    original code and is left unchanged here -- it needs checking against
    Schweizer 1987b (ApJS 64, 427) before the result is trusted.
    """
    e = sample_eccentricity(e_model, size=n_samples)
    M = np.random.uniform(0, 2 * np.pi, size=n_samples)
    E = solve_kepler(M, e)

    psi = np.sqrt(G / r * (1 + e * np.cos(E)))
    phi = np.arctan2(e * np.sin(E), np.sqrt(np.clip(1 - e**2, 0.0, None)))
    return psi, phi
